apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pubsub-app
spec:
  selector:
    matchLabels:
      app: gke-pubsub-app
  replicas: 3
  template:
    metadata:
      labels:
        app: gke-pubsub-app
    spec:
      containers:
      - name: flaskapp
        image: dhiraj6898/gke-pubsub-app:v1
        ports:
        - containerPort: 5000