apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pubsub-flaskapp
spec:
  selector:
    matchLabels:
      app: gke-pubsub-flaskapp
  replicas: 3
  template:
    metadata:
      labels:
        app: gke-pubsub-flaskapp
    spec:
      containers:
      - name: flaskapp
        image: dhiraj6898/gke-pubsub-flaskapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000