apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-flaskapp
spec:
  selector:
    matchLabels:
      app: kubernetes-flaskapp
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-flaskapp
    spec:
      containers:
      - name: flaskapp
        image: dhiraj6898/kubernetes-flaskapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000