apiVersion: v1
kind: Service
metadata:
  name: kubernetes-flaskapp
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-flaskapp
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP